// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Gear$ReactTemplate = require("../gear.bs.js");
var BSReact$ReactTemplate = require("../bSReact.bs.js");

var style = {
  width: "220px",
  height: "220px",
  display: "grid",
  gridTemplateRows: "1fr 1fr 1fr 1fr",
  gridTemplateColumns: "1fr 1fr 1fr 1fr"
};

var component = ReasonReact.statelessComponent("GearBoard");

function make(gears, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var children = List.map((function (r) {
                      return Gear$ReactTemplate.c(r, /* None */0, /* None */0, /* [] */0);
                    }), gears);
              return BSReact$ReactTemplate.div(/* Some */["gear-board"], /* None */0, /* :: */[
                          BSReact$ReactTemplate.div(/* None */0, /* Some */[style], children),
                          /* [] */0
                        ]);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

function c(gears, children) {
  var eta = make(gears, children);
  return ReasonReact.element(/* None */0, /* None */0, eta);
}

var GearBoard = /* module */[
  /* style */style,
  /* component */component,
  /* make */make,
  /* c */c
];

var component$1 = ReasonReact.statelessComponent("CodeBlock");

function make$1(children) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return BSReact$ReactTemplate.div(/* Some */["code-block"], /* None */0, /* :: */[
                          BSReact$ReactTemplate.pre(/* :: */[
                                BSReact$ReactTemplate.code(children),
                                /* [] */0
                              ]),
                          /* [] */0
                        ]);
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* subscriptions */component$1[/* subscriptions */13],
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

function c$1(children) {
  var eta = make$1(children);
  return ReasonReact.element(/* None */0, /* None */0, eta);
}

var CodeBlock = /* module */[
  /* component */component$1,
  /* make */make$1,
  /* c */c$1
];

function initialState() {
  return /* Problem */0;
}

function reducer(_, _$1) {
  return /* NoUpdate */0;
}

var component$2 = ReasonReact.statelessComponent("Problem");

function make$2() {
  return /* record */[
          /* debugName */component$2[/* debugName */0],
          /* reactClassInternal */component$2[/* reactClassInternal */1],
          /* handedOffState */component$2[/* handedOffState */2],
          /* willReceiveProps */component$2[/* willReceiveProps */3],
          /* didMount */component$2[/* didMount */4],
          /* didUpdate */component$2[/* didUpdate */5],
          /* willUnmount */component$2[/* willUnmount */6],
          /* willUpdate */component$2[/* willUpdate */7],
          /* shouldUpdate */component$2[/* shouldUpdate */8],
          /* render */(function () {
              return BSReact$ReactTemplate.div(/* Some */["problem"], /* None */0, /* :: */[
                          BSReact$ReactTemplate.h1(/* :: */[
                                "Gear Out!",
                                /* [] */0
                              ]),
                          /* :: */[
                            BSReact$ReactTemplate.p(/* :: */[
                                  "オフラインリアルタイムどう書く E26 問題",
                                  /* [] */0
                                ]),
                            /* :: */[
                              BSReact$ReactTemplate.h2(/* :: */[
                                    "問題文",
                                    /* [] */0
                                  ]),
                              /* :: */[
                                c(/* :: */[
                                      1,
                                      /* :: */[
                                        2,
                                        /* :: */[
                                          2,
                                          /* :: */[
                                            1,
                                            /* :: */[
                                              4,
                                              /* :: */[
                                                3,
                                                /* :: */[
                                                  1,
                                                  /* :: */[
                                                    2,
                                                    /* :: */[
                                                      1,
                                                      /* :: */[
                                                        1,
                                                        /* :: */[
                                                          2,
                                                          /* :: */[
                                                            3,
                                                            /* :: */[
                                                              1,
                                                              /* :: */[
                                                                4,
                                                                /* :: */[
                                                                  1,
                                                                  /* :: */[
                                                                    4,
                                                                    /* [] */0
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ], /* [] */0),
                                /* :: */[
                                  BSReact$ReactTemplate.p(/* :: */[
                                        "図のように歯車が設置されています。歯車には印が付いていて、その場所に応じて「上」「右」「下」「左」の向きがあります。",
                                        /* [] */0
                                      ]),
                                  /* :: */[
                                    BSReact$ReactTemplate.p(/* :: */[
                                          "「上」向きの歯車を、",
                                          /* :: */[
                                            BSReact$ReactTemplate.b(/* :: */[
                                                  "正しい向き",
                                                  /* [] */0
                                                ]),
                                            /* :: */[
                                              "の歯車とします。",
                                              /* [] */0
                                            ]
                                          ]
                                        ]),
                                    /* :: */[
                                      BSReact$ReactTemplate.p(/* :: */[
                                            "歯車は時計回りに回転させる事ができます。",
                                            /* [] */0
                                          ]),
                                      /* :: */[
                                        BSReact$ReactTemplate.p(/* :: */[
                                              "ある歯車を回転させると、その上下左右の歯車が",
                                              /* :: */[
                                                BSReact$ReactTemplate.b(/* :: */[
                                                      "反時計回りに",
                                                      /* [] */0
                                                    ]),
                                                /* :: */[
                                                  "回転します。",
                                                  /* [] */0
                                                ]
                                              ]
                                            ]),
                                        /* :: */[
                                          BSReact$ReactTemplate.p(/* :: */[
                                                "全ての歯車を「正しい向き」にするには、どのような順番で歯車を回していけば良いでしょうか？",
                                                /* [] */0
                                              ]),
                                          /* :: */[
                                            BSReact$ReactTemplate.h2(/* :: */[
                                                  "入力",
                                                  /* [] */0
                                                ]),
                                            /* :: */[
                                              BSReact$ReactTemplate.p(/* :: */[
                                                    "入力には2つの形式があり、好きな方を選ぶ事ができます。どちらも、表される状況は同じです。",
                                                    /* [] */0
                                                  ]),
                                              /* :: */[
                                                BSReact$ReactTemplate.p(/* :: */[
                                                      "一つは、全て1行の文字列で受け取る形式です。最初に縦横の大きさがあり、パイプを挟んでその後ろに歯車の状態が並びます。",
                                                      /* [] */0
                                                    ]),
                                                /* :: */[
                                                  BSReact$ReactTemplate.p(/* :: */[
                                                        "歯車の状態は全て数字で表され、「上」が \"1\" 、「右」が \"2\" 、「下」が \"3\" 、「左」が \"4\" です。",
                                                        /* [] */0
                                                      ]),
                                                  /* :: */[
                                                    BSReact$ReactTemplate.p(/* :: */[
                                                          "連続する数字が横一列の歯車を表し、各横列をカンマで区切ります。",
                                                          /* [] */0
                                                        ]),
                                                    /* :: */[
                                                      c$1(/* :: */[
                                                            "\"4|0000,0000,0000,0000\"",
                                                            /* [] */0
                                                          ]),
                                                      /* :: */[
                                                        BSReact$ReactTemplate.p(/* :: */[
                                                              "もう一つは、複数行で受け取る形式です。最初の行に縦横の大きさ N が出力され、以下 N 行に歯車の状態が出力されます。",
                                                              /* [] */0
                                                            ]),
                                                        /* :: */[
                                                          BSReact$ReactTemplate.p(/* :: */[
                                                                "歯車の状態は同じく「上」が \"1\" 、「右」が \"2\" 、「下」が \"3\" 、「左」が \"4\" ですが、各々の数字が空白区切りで表されます。",
                                                                /* [] */0
                                                              ]),
                                                          /* :: */[
                                                            c$1(/* :: */[
                                                                  "4\n0 0 0 0\n0 0 0 0\n0 0 0 0\n0 0 0 0",
                                                                  /* [] */0
                                                                ]),
                                                            /* :: */[
                                                              BSReact$ReactTemplate.h2(/* :: */[
                                                                    "出力",
                                                                    /* [] */0
                                                                  ]),
                                                              /* :: */[
                                                                BSReact$ReactTemplate.p(/* :: */[
                                                                      "回答は、歯車を動かす手順を1行ずつ出力してください。",
                                                                      /* [] */0
                                                                    ]),
                                                                /* :: */[
                                                                  BSReact$ReactTemplate.p(/* :: */[
                                                                        "動かす歯車は x 軸と y 軸の座標で指定してください。",
                                                                        /* [] */0
                                                                      ]),
                                                                  /* :: */[
                                                                    BSReact$ReactTemplate.p(/* :: */[
                                                                          "1度の操作で、必ず1つの歯車を時計回りに90度だけ回す必要があります。それ以外の操作を行う事はできません。",
                                                                          /* [] */0
                                                                        ]),
                                                                    /* :: */[
                                                                      BSReact$ReactTemplate.p(/* :: */[
                                                                            "各行には歯車の座標の他に余計な出力をしてはいけません。",
                                                                            /* [] */0
                                                                          ]),
                                                                      /* :: */[
                                                                        BSReact$ReactTemplate.p(/* :: */[
                                                                              "不正な行があった場合、その時点で採点は中断され、テストは失敗します。",
                                                                              /* [] */0
                                                                            ]),
                                                                        /* :: */[
                                                                          BSReact$ReactTemplate.h3(/* :: */[
                                                                                "出力例1",
                                                                                /* [] */0
                                                                              ]),
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]);
            }),
          /* initialState */component$2[/* initialState */10],
          /* retainedProps */component$2[/* retainedProps */11],
          /* reducer */component$2[/* reducer */12],
          /* subscriptions */component$2[/* subscriptions */13],
          /* jsElementWrapped */component$2[/* jsElementWrapped */14]
        ];
}

function c$2(children) {
  var eta = make$2(children);
  return ReasonReact.element(/* None */0, /* None */0, eta);
}

exports.GearBoard = GearBoard;
exports.CodeBlock = CodeBlock;
exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component$2;
exports.make = make$2;
exports.c = c$2;
/* component Not a pure module */
