// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var BSReact$ReactTemplate = require("./bSReact.bs.js");
var Problem$ReactTemplate = require("./pages/problem.bs.js");

function initialState() {
  return /* Problem */0;
}

function reducer(_, _$1) {
  return /* NoUpdate */0;
}

var component = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (match !== 0) {
                return BSReact$ReactTemplate.div(/* None */0, /* None */0, /* [] */0);
              } else {
                return Problem$ReactTemplate.c(/* [] */0);
              }
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

function c(children) {
  var eta = make(children);
  return ReasonReact.element(/* None */0, /* None */0, eta);
}

exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component;
exports.make = make;
exports.c = c;
/* component Not a pure module */
