// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function empty() {
  return { };
}

function div(class_name, style, children) {
  var tmp = { };
  if (class_name) {
    tmp.className = class_name[0];
  }
  if (style) {
    tmp.style = style[0];
  }
  var props = tmp;
  return ReasonReact.createDomElement("div", props, $$Array.of_list(children));
}

function code(children) {
  return ReasonReact.createDomElement("code", { }, $$Array.of_list(children));
}

function pre(children) {
  return ReasonReact.createDomElement("pre", { }, $$Array.of_list(children));
}

function h1(children) {
  return ReasonReact.createDomElement("h1", { }, $$Array.of_list(children));
}

function h2(children) {
  return ReasonReact.createDomElement("h2", { }, $$Array.of_list(children));
}

function h3(children) {
  return ReasonReact.createDomElement("h3", { }, $$Array.of_list(children));
}

function p(children) {
  return ReasonReact.createDomElement("p", { }, $$Array.of_list(children));
}

function b(children) {
  return ReasonReact.createDomElement("b", { }, $$Array.of_list(children));
}

var RR = 0;

var RD = 0;

exports.RR = RR;
exports.RD = RD;
exports.empty = empty;
exports.div = div;
exports.code = code;
exports.pre = pre;
exports.h1 = h1;
exports.h2 = h2;
exports.h3 = h3;
exports.p = p;
exports.b = b;
/* ReasonReact Not a pure module */
