// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var BSReact$ReactTemplate = require("./bSReact.bs.js");

var component = ReasonReact.statelessComponent("Gear");

function make(r, $staropt$star, _, _$1) {
  var class_name = $staropt$star ? $staropt$star[0] : "";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var r$1 = String(r);
              var klass = "gear-box r" + (String(r$1) + (" " + (String(class_name) + "")));
              return BSReact$ReactTemplate.div(/* Some */[klass], /* None */0, /* :: */[
                          BSReact$ReactTemplate.div(/* Some */["gear"], /* None */0, /* [] */0),
                          /* :: */[
                            BSReact$ReactTemplate.div(/* Some */["arrow"], /* None */0, /* [] */0),
                            /* [] */0
                          ]
                        ]);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

function c(r, class_name, on_click, children) {
  var eta = make(r, class_name, on_click, children);
  return ReasonReact.element(/* None */0, /* None */0, eta);
}

exports.component = component;
exports.make = make;
exports.c = c;
/* component Not a pure module */
