// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReactTemplate = require("./app.bs.js");

ReactDOMRe.renderToElementWithId(App$ReactTemplate.c(/* [] */0), "app");

/*  Not a pure module */
